stages:
  - tests
register_tests:
  stage: tests
  image: hdlc/ghdl:yosys
  before_script:
    - yosys --version
  script:
    - cd formal/register_tests
    - ./run_tests.sh | tee docker_register_tests.log
  artifacts:
    paths:
    - formal/register_tests/docker_register_tests.log
    expire_in: 6 week


issue_ys_639_tests:
  stage: tests
  image: hdlc/ghdl:yosys
  before_script:
    - yosys --version
  script:
    - cd formal
    - pushd example-yosys-issue639/
    - ./run-all-yosys-equiv.sh >> yosys_equiv.log
    - ./check-results.sh | tee equiv_check.log
    - popd
  artifacts:
    paths:
    - formal/example-yosys-issue639/*.log
    expire_in: 6 week
