stages:
  - tests
register_tests:
  stage: tests
  image: hdlc/ghdl:yosys
  before_script:
    - yosys --version
  script:
    - cd formal/register_tests
    - ./run_tests.sh | tee docker_register_tests.log
  artifacts:
    paths:
    - formal/register_tests/docker_register_tests.log
    expire_in: 6 week


issue_ys_639_tests:
  stage: tests
  image: hdlc/ghdl:yosys
  before_script:
    - yosys --version
  script:
    - cd formal
    - cd example-yosys-issue639/
    - ./run-all-yosys-equiv.sh >> yosys_equiv.log
    - ./check-results.sh | tee equiv_check.log
  artifacts:
    paths:
    - formal/example-yosys-issue639/*.log
    expire_in: 6 week

ghdl_synth_libs:
  stage: tests
  image: hdlc/ghdl:yosys
  before_script:
    - yosys --version
  script:
    - cd synth/
    - cd vhdl-pkgs-custom-lib/
    - bash run-yosys.sh | tee ghdl_yosys_synth.log
    - cd ../
    - cd vhdl-pkgs-lib-work/
    - bash run-yosys.sh | tee ghdl_yosys_synth.log
  artifacts:
    paths:
    - synth/vhdl-pkgs-*/ghdl_yosys_synth.log
    expire_in: 6 week
