stages:
  - tests
register_tests:
  stage: tests
  image: hdlc/ghdl:yosys
  before_script:
    - yosys --version
  script:
    - cd formal/register_tests
    - ./run_tests.sh | tee docker_register_tests.log
  artifacts:
    paths:
    - formal/register_tests/docker_register_tests.log
    expire_in: 6 week


issue_tests:
  stage: tests
  image: hdlc/ghdl:yosys
  before_script:
    - yosys --version
  script:
    - cd formal
    - ./example-from-issue639-run-all-yosys-equiv.sh >> docker_equiv_dump.log
    - ./example-from-issue639-check-results.sh | tee docker_equiv_check.log
  artifacts:
    paths:
    - formal/docker_equiv_dump.log
    - formal/docker_equiv_check.log
    expire_in: 6 week
